<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.w3.org/1999/xhtml">
    <xsl:output indent="yes" method="html" />

    <xsl:template name="sidebar-footer">
        Documentation is generated by <a href="http://www.phpdoc.org" target="_top">
        phpDocumentor <xsl:value-of select="$version" />
        </a>
    </xsl:template>

</xsl:stylesheet>
